name: Generate Markdown File

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # or your desired version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install polars seaborn matplotlib  # or other required packages

    - name: Generate Markdown File
      run: |
        python3 markdownGenerater.py  # Adjust this to the path to your Python script

    - name: Commit and push if changes
      run: |
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update markdown file" && git push)
